import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { Toaster } from 'sonner'
import Navbar from '../components/navbar/Navbar'
import { ThemeProvider } from '../components/theme-provider'
import AuthSessionProvider from '../providers'
import './globals.css'
import StoreProvider from './StoreProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
      <html lang='en' suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} container mx-auto min-h-screen antialiased`}
          suppressHydrationWarning
        >
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <StoreProvider>
              <div className='relative'>
                <Navbar />
              </div>
              {children}
            </StoreProvider>
          </ThemeProvider>
          <Toaster position='top-center' closeButton richColors />
        </body>
      </html>
  )
}
